cors:
  originPatterns: http://localhost:3000,http://localhost:8080,https://www.fabriciounix.com.br
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot?useTimezone=true&serverTimezone=UTC
    username: root
    password: Ximbiquinha2015&
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
spring-doc:
  path-to-match:
    - /api/**/v1/**

